### Example to get user 
GET http://localhost:3100/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJlbWFpbCI6InRlc3RfdXNlcjNAZ21haWwuY29tIiwiaWF0IjoxNzExNjE5MzQyLCJleHAiOjE3MTE2MjAyNDJ9.ZvgUaW5612UEjcRf4qxG1v_dwZQIKJ8Vso_YCcvL3tA

